name: Autodeploy
on:
    push:
        branches:
            - main
jobs:
    run_pull:
        name: Deploy to Server
        runs-on: ubuntu-latest

        steps:
          - name: install ssh keys
            uses: appleboy/ssh-action@master
            with:
              host: ${{secrets.SSH_HOST}}
              username: ${{secrets.SSH_USER}}
              key: ${{secrets.SSH_KEY}}
              script: |
                bash /Moon_light_bot/update.sh