name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        WORK_DIR: ${{ secrets.WORK_DIR }}
        MAIN_BRANCH: ${{ secrets.MAIN_BRANCH }}
      run: |
        echo ${{secrets.SSH_PRIVATE_KEY}} | sed 's/./&/g'
        echo ${{secrets.SSH_HOST}} | sed 's/./&/g'
        echo ${{secrets.SSH_USER}} | sed 's/./&/g'
        echo ${{secrets.WORK_DIR}} | sed 's/./&/g'
        echo ${{secrets.MAIN_BRANCH}} | sed 's/./&/g'
        
        
